### ISSUE TITLE
Unable to compile alt-coins

### ISSUE THREAD

**Issue by Thireus** [znort987/blockparser#17]
Hi,

The normal -DBITCOIN compilation is OK.

But, I'm not able to compile blockparser for alt-coins (i.e. Peercoin or Litecoin). I have the following errors when I build the utility after commenting -DBITCOIN and uncommenting -DPEERCOIN or -DLITECOIN from the Makefile:

~/blockparser> make
c++ -- callback.cpp
c++ -- cb/allBalances.cpp
c++ -- cb/closure.cpp
c++ -- cb/dumpTX.cpp
c++ -- cb/help.cpp
c++ -- cb/pristine.cpp
c++ -- cb/rewards.cpp
c++ -- cb/simpleStats.cpp
c++ -- cb/sql.cpp
c++ -- cb/taint.cpp
c++ -- cb/transactions.cpp
cc -- h9/blake.c
cc -- h9/bmw.c
cc -- h9/cubehash.c
cc -- h9/echo.c
cc -- h9/groestl.c
cc -- h9/jh.c
cc -- h9/keccak.c
cc -- h9/luffa.c
cc -- h9/shavite.c
In file included from cb/dumpTX.cpp:4:0:
./util.h:289:5: error: expected identifier before ‘)’ token
In file included from cb/taint.cpp:25:0:
./util.h:289:5: error: expected identifier before ‘)’ token
In file included from cb/allBalances.cpp:4:0:
./util.h:289:5: error: expected identifier before ‘)’ token
In file included from cb/sql.cpp:4:0:
./util.h:289:5: error: expected identifier before ‘)’ token
In file included from cb/pristine.cpp:4:0:
./util.h:289:5: error: expected identifier before ‘)’ token
In file included from cb/transactions.cpp:5:0:
./util.h:289:5: error: expected identifier before ‘)’ token
In file included from cb/simpleStats.cpp:4:0:
./util.h:289:5: error: expected identifier before ‘)’ token
In file included from callback.cpp:3:0:
./util.h:289:5: error: expected identifier before ‘)’ token
In file included from cb/rewards.cpp:4:0:
./util.h:289:5: error: expected identifier before ‘)’ token
cc -- h9/simd.c
cb/dumpTX.cpp: In static member function ‘static void DumpTX::showScriptInfo(const uint8_t*, uint64_t)’:
cb/dumpTX.cpp:254:46: error: too few arguments to function ‘void hash160ToAddr(uint8_t*, const uint8_t*, int)’
In file included from cb/dumpTX.cpp:4:0:
./util.h:262:10: note: declared here
cb/allBalances.cpp: In member function ‘virtual void AllBalances::wrapup()’:
cb/allBalances.cpp:331:48: error: too few arguments to function ‘void hash160ToAddr(uint8_t*, const uint8_t*, int)’
In file included from cb/allBalances.cpp:4:0:
./util.h:262:10: note: declared here
cb/sql.cpp: In member function ‘virtual void SQLDump::endOutput(const uint8_t*, uint64_t, const uint8_t*, uint64_t, const uint8_t*, uint64_t)’:
cb/sql.cpp:248:64: error: too few arguments to function ‘void hash160ToAddr(uint8_t*, const uint8_t*, int)’
In file included from cb/sql.cpp:4:0:
./util.h:262:10: note: declared here
make: *** [.objs/pristine.o] Erreur 1
make: *** Attente des tâches non terminées....
make: *** [.objs/simpleStats.o] Erreur 1
make: *** [.objs/rewards.o] Erreur 1
make: *** [.objs/callback.o] Erreur 1
make: *** [.objs/dumpTX.o] Erreur 1
make: *** [.objs/transactions.o] Erreur 1
make: *** [.objs/sql.o] Erreur 1
make: *** [.objs/allBalances.o] Erreur 1
make: *** [.objs/taint.o] Erreur 1
In file included from cb/closure.cpp:4:0:
./util.h:289:5: error: expected identifier before ‘)’ token
cb/closure.cpp: In member function ‘virtual void Closure::wrapup()’:
cb/closure.cpp:139:39: error: too few arguments to function ‘void hash160ToAddr(uint8_t*, const uint8_t*, int)’
In file included from cb/closure.cpp:4:0:
./util.h:262:10: note: declared here
make: *** [.objs/closure.o] Erreur 1

Kind regards,
Thi.

**Comment by vertoe** [comment]
ah bummer, i was debugging this for hours. REPLACE! damn ...

**Comment by znort987** [comment]
Ideally, this should be made a dynamic option, not a compile time thing.
Patches welcome.
