### ISSUE TITLE
Multisig support?

### ISSUE THREAD

**Issue by andr3w321** [znort987/blockparser#25]
Any plans for multisig support?

**Comment by znort987** [comment]
I'd have to read up on it, understand how it works and implement it.
It'd also be a very good opportunity to upgrade the script parsing routines in util.cpp
to modern standard (i.e. pay to script, multi-sig, etc ...).
There are also (I think) a number of places in the code that assume that payout is to
a single address (e.g. allbalances). Multi-sig kind of breaks that assumption, so a lot
of thing would need to be re-thought.
TBH, I simply don't have the time right now.
Patches and poull requests are welcome though.

**Comment by andr3w321** [comment]
I posted this job on elance and hoping to get it implemented.  I'll place the equivalent of $100 USD in BTC bounty on this if a random wants to fix it before I hire someone.

**Comment by jahrsg** [comment]
Hi. Have you found somebody at Elance? Is this bounty actual now?

**Comment by andr3w321** [comment]
I hired someone on elance for close to $400.  They are currently working on it but have not pushed any code yet

**Comment by jahrsg** [comment]
Please,  contact me (scruffy@nakamoto.pw) if they failed to complete it,  I can try to implement this. Sorry for flood in comments, I can't find your contact info in your profile.)

**Comment by znort987** [comment]
OK.

Now that I've been able to take the time to understand multi-sig in its various
incarnations (p2sh and naked) I think I've found a way to tackle it.

I have just pushed commit that should tenatively solve the problem.

For P2SH, it's a no-brainer, just a matter of coding the addresses properly.

For naked multi-sig, I think I've found a neat trick, inspired by P2SH:
I compute a hash160 of (m, n, and all the hashes of the controlling keys),
and encode this into a new type of address that starts with '4'.

See the README for explanations and examples.

@andr3w321 : if you're still feeling generous, I'll gladly take a BTC tip :)

**Comment by andr3w321** [comment]
Sweet I'll take a look at this when I have some time.  Unfortunately I recently sold my site: http://bitcoinrichlist.com which makes heavy use of your scripts.  I sent you a small tip and notified the new owner

**Comment by znort987** [comment]
Thanks for the tip !

 


    On Thursday, November 19, 2015 7:16 AM, andr3w321 <notifications@github.com> wrote:
 

 Sweet I'll take a look at this when I have some time. Unfortunately I recently sold my site: http://bitcoinrichlist.com which makes heavy use of your scripts. I sent you a small tip and notified the new owner—
