### ISSUE TITLE
Segmentation Fault at block 225500 while dumping the blockchain

### ISSUE THREAD

**Issue by ghost** [znort987/blockparser#3]
I want to dump the blockchain, so i run:

parser sqldump

It starts to dump and seems to work fine, until block 225500 is reached. It then ends with a segmentation fault:

block=  224000 nbOutputs=31901131
block=  224500 nbOutputs=32325594
block=  225000 nbOutputs=32761533
block=  225500 nbOutputs=33208004
Segmentation Fault

This error is reproducable for me, i downloaded the sources three days ago, so they should be up to date.

**Comment by privatenode** [comment]
[71549.799128] show_signal_msg: 15 callbacks suppressed
[71549.799131] parser[1894]: segfault at 7ff1bede7414 ip 0000000000430d22 sp 00007ffdcdc12170 error 4 in parser[400000+47000]

**Comment by reppolice** [comment]
I've got a 15GB machine and it shows 90% of RAM goes to the parser and it will be running for many hours, hope the memory will not increase any further but I can see why my 8GB machine also segfaults
