### ISSUE TITLE
lots of XXXXX.. addresses in allballances ?

### ISSUE THREAD

**Issue by sologap** [znort987/blockparser#31]
i've dumped all addresses but after the address number 500'ish all addreses are XXXXXXX.. 

did i miss something ?

i used ./parser allBalances >allBalances.txt

**Comment by znort987** [comment]
This is by design. Converting addresses to their ascii representation is costly. So only the first N are converted, the rest is replaced by X. Luckily, N can be changed using  flag.

./parser allBalances --help will reveal all
