### ISSUE TITLE
bitcoin 0.10 blockchain archive

### ISSUE THREAD

**Issue by gbianchi** [znort987/blockparser#33]
Someone use this with bitcoin-qt 0.10 ?
Whith my blockchain archive, the blockparser crash.

**Comment by znort987** [comment]
I don't think the crash is because of the version of bitcoin-qtyou're using. Can you strace ?



     On Wednesday, July 15, 2015 7:50 AM, gbianchi <notifications@github.com> wrote:
   

 Someone use this with bitcoin-qt 0.10 ?
Whith my blockchain archive, the blockparser crash.—

**Comment by znort987** [comment]
Also, note that there is an option for allbalances that stops processing after a given block number and gives you a snapshot of the state of the ledger at that time.
Closing this until I get more info.
