### ISSUE TITLE
Question - What is gExpectedMagic?

### ISSUE THREAD

**Issue by programador9099** [znort987/blockparser#34]
I want to use this program with Cryptoescudo / CESC, what is the gExpectedMagic for CryptoEscudo? Where can i find it?

**Comment by znort987** [comment]
gExpectedMagic are the bytes that mark the beginning of a block in theblockchain files.
You need to read the source code for Cryptoescudo to find those bytes forthat particular alt
 


     On Wednesday, August 26, 2015 6:36 AM, Alexandre Badalo <notifications@github.com> wrote:
   

 I want to use this program with Cryptoescudo / CESC, what is the gExpectedMagic for CryptoEscudo? Where can i find it?—

**Comment by programador9099** [comment]
And in which file I found that? I have the source code 

On 25 de Setembro de 2015 16:55:17 WEST, znort987 <notifications@github.com> wrote:
>
>gExpectedMagic are the bytes that mark the beginning of a block in
>theblockchain files.
>You need to read the source code for Cryptoescudo to find those bytes
>forthat particular alt
> 
>
>
>On Wednesday, August 26, 2015 6:36 AM, Alexandre Badalo
><notifications@github.com> wrote:
>   
>
>I want to use this program with Cryptoescudo / CESC, what is the
>gExpectedMagic for CryptoEscudo? Where can i find it?—
>Reply to this email directly or view it on GitHub.  
>
>  
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/znort987/blockparser/issues/34#issuecomment-143260000

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by znort987** [comment]
assuming your alt is based on the bitcoin codebase,

file src/chainparam.cpp
around line 290, look for the initialization of a variable caled pchMessageStart 


     On Friday, September 25, 2015 8:57 AM, Alexandre Badalo <notifications@github.com> wrote:
   

 And in which file I found that? I have the source code 

On 25 de Setembro de 2015 16:55:17 WEST, znort987 <notifications@github.com> wrote:
>
>gExpectedMagic are the bytes that mark the beginning of a block in
>theblockchain files.
>You need to read the source code for Cryptoescudo to find those bytes
>forthat particular alt
> 
>
>
>On Wednesday, August 26, 2015 6:36 AM, Alexandre Badalo
><notifications@github.com> wrote:
> 
>
>I want to use this program with Cryptoescudo / CESC, what is the
>gExpectedMagic for CryptoEscudo? Where can i find it?—
>Reply to this email directly or view it on GitHub. 
>
> 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/znort987/blockparser/issues/34#issuecomment-143260000

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.—

**Comment by programador9099** [comment]
I think it's based on litecoin, no chainparam.cpp found 

On 25 de Setembro de 2015 17:15:26 WEST, znort987 <notifications@github.com> wrote:
>assuming your alt is based on the bitcoin codebase,
>
>file src/chainparam.cpp
>around line 290, look for the initialization of a variable caled
>pchMessageStart 
>
>
>On Friday, September 25, 2015 8:57 AM, Alexandre Badalo
><notifications@github.com> wrote:
>   
>
> And in which file I found that? I have the source code 
>
>On 25 de Setembro de 2015 16:55:17 WEST, znort987
><notifications@github.com> wrote:
>>
>>gExpectedMagic are the bytes that mark the beginning of a block in
>>theblockchain files.
>>You need to read the source code for Cryptoescudo to find those bytes
>>forthat particular alt
>> 
>>
>>
>>On Wednesday, August 26, 2015 6:36 AM, Alexandre Badalo
>><notifications@github.com> wrote:
>> 
>>
>>I want to use this program with Cryptoescudo / CESC, what is the
>>gExpectedMagic for CryptoEscudo? Where can i find it?—
>>Reply to this email directly or view it on GitHub. 
>>
>> 
>>
>>---
>>Reply to this email directly or view it on GitHub:
>>https://github.com/znort987/blockparser/issues/34#issuecomment-143260000
>
>-- 
>Sent from my Android device with K-9 Mail. Please excuse my brevity.—
>Reply to this email directly or view it on GitHub. 
>
>  
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/znort987/blockparser/issues/34#issuecomment-143265713

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by znort987** [comment]
Doing this:

    git clone git@github.com:Marcdnd/cryptoescudo.git
    cd cryptoescudo
    find . -type f -exec grep 'pchMessageStart' {} \; -print

yields, among other things:

    unsigned char pchMessageStart[4] = { 0xfb, 0xc0, 0xb6, 0xdb };
