### ISSUE TITLE
Low speed

### ISSUE THREAD

**Issue by GilAlexander** [znort987/blockparser#35]
I have a vultr instance: Ubuntu 14.10 x64, 8 CPU (some kind of xeon 3.2-3.4ghz), 16GB RAM, 300GB SSD and 10GB swap. I've build blockparser and run: ./parser balance > all.txt
When the blockchain was without index (txindex=0 in bitcoin.conf), it worked very slow.
Now I set txindex=1 and run ./bitcoind -reindex. ~230k blocks have been reindexed so far and I've run parser again - it took 830 secs to parse 50 MegaAddr (there are ~88kk) - it's quite faster but the speed is falling.

Do I need to build full index? If yes, pls note that in your main manual.

UPD. Looks like I need more ram - 16gb is completely used.

**Comment by znort987** [comment]
Blockparser doesn't use the index. It only processes the raw chain.
 


     On Tuesday, September 1, 2015 5:06 AM, GilAlexander <notifications@github.com> wrote:
   

 I have a vultr instance: Ubuntu 14.10 x64, 8 CPU (some kind of xeon 3.2-3.4ghz), 16GB RAM, 300GB SSD and 10GB swap. I've build blockparser and run: ./parser balance > all.txt
When the blockchain was without index (txindex=0 in bitcoin.conf), it worked very slow.
Now I set txindex=1 and run ./bitcoind -reindex. ~230k blocks have been reindexed so far and I've run parser again - it took 830 secs to parse 50 MegaAddr (there are ~88kk) - it's quite faster but the speed is falling.Do I need to build full index? If yes, pls note that in your main manual.—
