### ISSUE TITLE
error with blockparser

### ISSUE THREAD

**Issue by makabress** [znort987/blockparser#36]
@ubuntu:~/blockparser$ make
lnk -- parser
/tmp/cciT6l1M.ltrans8.ltrans.o: In function `Rewards::endOutput(unsigned char const*, unsigned long, unsigned char const*, unsigned long, unsigned char const*, unsigned long)':
cciT6l1M.ltrans8.o:(.text+0xba2): undefined reference to`EC_KEY_new_by_curve_name'
cciT6l1M.ltrans8.o:(.text+0xbc4): undefined reference to `o2i_ECPublicKey'
cciT6l1M.ltrans8.o:(.text+0xbd8): undefined reference to`EC_KEY_set_conv_form'
cciT6l1M.ltrans8.o:(.text+0xbe7): undefined reference to `i2o_ECPublicKey'
cciT6l1M.ltrans8.o:(.text+0xbf4): undefined reference to`EC_KEY_free'
cciT6l1M.ltrans8.o:(.text+0xc48): undefined reference to `EC_KEY_free'
/tmp/cciT6l1M.ltrans12.ltrans.o: In function`SQLDump::startBlock(Block const_, unsigned long)':
cciT6l1M.ltrans12.o:(.text+0x8a4): undefined reference to `SHA256_Init'
cciT6l1M.ltrans12.o:(.text+0x8b6): undefined reference to`SHA256_Update'
cciT6l1M.ltrans12.o:(.text+0x8c3): undefined reference to `SHA256_Final'
cciT6l1M.ltrans12.o:(.text+0x8cd): undefined reference to`SHA256_Init'
cciT6l1M.ltrans12.o:(.text+0x8df): undefined reference to `SHA256_Update'
cciT6l1M.ltrans12.o:(.text+0x8ec): undefined reference to`SHA256_Final'
/tmp/cciT6l1M.ltrans22.ltrans.o: In function `addrToHash160(unsigned char_, unsigned char const_, bool, bool) [clone .constprop.114]':
cciT6l1M.ltrans22.o:(.text+0x14d): undefined reference to `BN_set_word'
cciT6l1M.ltrans22.o:(.text+0x1d5): undefined reference to`BN_mul_word'
cciT6l1M.ltrans22.o:(.text+0x1e4): undefined reference to `BN_add_word'
cciT6l1M.ltrans22.o:(.text+0x1fe): undefined reference to`BN_bn2mpi'
cciT6l1M.ltrans22.o:(.text+0x21c): undefined reference to `BN_bn2mpi'
cciT6l1M.ltrans22.o:(.text+0x521): undefined reference to`BN_CTX_new'
cciT6l1M.ltrans22.o:(.text+0x530): undefined reference to `BN_CTX_init'
cciT6l1M.ltrans22.o:(.text+0x535): undefined reference to`BN_new'
/tmp/cciT6l1M.ltrans22.ltrans.o: In function `hash160ToAddr(unsigned char_, unsigned char const_, unsigned char) [clone .constprop.100]':
cciT6l1M.ltrans22.o:(.text+0xef6): undefined reference to `BN_mpi2bn'
cciT6l1M.ltrans22.o:(.text+0xf23): undefined reference to`BN_copy'
cciT6l1M.ltrans22.o:(.text+0xf2f): undefined reference to `BN_get_word'
cciT6l1M.ltrans22.o:(.text+0xf6e): undefined reference to`BN_div'
cciT6l1M.ltrans22.o:(.text+0x1084): undefined reference to `BN_CTX_new'
cciT6l1M.ltrans22.o:(.text+0x1093): undefined reference to`BN_CTX_init'
cciT6l1M.ltrans22.o:(.text+0x1098): undefined reference to `BN_new'
cciT6l1M.ltrans22.o:(.text+0x10a4): undefined reference to`BN_new'
cciT6l1M.ltrans22.o:(.text+0x10b0): undefined reference to `BN_new'
cciT6l1M.ltrans22.o:(.text+0x10bc): undefined reference to`BN_new'
cciT6l1M.ltrans22.o:(.text+0x10d4): undefined reference to `BN_set_word'
/tmp/cciT6l1M.ltrans23.ltrans.o: In function`buildBlockHeaders() [clone .lto_priv.219]':
cciT6l1M.ltrans23.o:(.text+0xfd8): undefined reference to `SHA256_Init'
cciT6l1M.ltrans23.o:(.text+0xfee): undefined reference to`SHA256_Update'
cciT6l1M.ltrans23.o:(.text+0xffe): undefined reference to `SHA256_Final'
cciT6l1M.ltrans23.o:(.text+0x100b): undefined reference to`SHA256_Init'
cciT6l1M.ltrans23.o:(.text+0x1020): undefined reference to `SHA256_Update'
cciT6l1M.ltrans23.o:(.text+0x1030): undefined reference to`SHA256_Final'
/tmp/cciT6l1M.ltrans30.ltrans.o: In function `sha256(unsigned char_, unsigned char const_, unsigned long)':
cciT6l1M.ltrans30.o:(.text+0x15): undefined reference to `SHA256_Init'
cciT6l1M.ltrans30.o:(.text+0x23): undefined reference to`SHA256_Update'
cciT6l1M.ltrans30.o:(.text+0x2e): undefined reference to `SHA256_Final'
/tmp/cciT6l1M.ltrans30.ltrans.o: In function`solveOutputScript(unsigned char_, unsigned char const_, unsigned long, unsigned char_)':
cciT6l1M.ltrans30.o:(.text+0x113): undefined reference to `SHA256_Init'
cciT6l1M.ltrans30.o:(.text+0x126): undefined reference to`SHA256_Update'
cciT6l1M.ltrans30.o:(.text+0x133): undefined reference to `SHA256_Final'
cciT6l1M.ltrans30.o:(.text+0x13d): undefined reference to`RIPEMD160_Init'
cciT6l1M.ltrans30.o:(.text+0x14f): undefined reference to `RIPEMD160_Update'
cciT6l1M.ltrans30.o:(.text+0x15c): undefined reference to`RIPEMD160_Final'
cciT6l1M.ltrans30.o:(.text+0x1d2): undefined reference to `RIPEMD160_Init'
cciT6l1M.ltrans30.o:(.text+0x1e4): undefined reference to`RIPEMD160_Update'
cciT6l1M.ltrans30.o:(.text+0x1f1): undefined reference to `RIPEMD160_Final'
collect2: error: ld returned 1 exit status
Makefile:310: recipe for target 'parser' failed
make: **\* [parser] Error 1

**Comment by makabress** [comment]
hi 
i recive this error when i try tu use "make"
can you help pls

thank you

**Comment by makabress** [comment]
any idea plz

**Comment by 6coind** [comment]
did you install ALL the dependencies?

**Comment by makabress** [comment]
yes , and removed and reinstalled many time but i get the same problem

**Comment by znort987** [comment]
What platform are you trying to compile on ?
This looks like your link phase fails to link against openssl
Can you post the output of the following command:

    make clean
    make -n

**Comment by makabress** [comment]
:~/blockparser$ make clean
rm -r -f *.o *.i .objs .deps *.d parser

:~/blockparser$ make -n
echo c++ -- cb/allBalances.cpp
mkdir -p .deps
mkdir -p .objs
g++ -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -c cb/allBalances.cpp -o .objs/allBalances.o
mv .objs/allBalances.d .deps
echo c++ -- cb/closure.cpp
mkdir -p .deps
mkdir -p .objs
g++ -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -c cb/closure.cpp -o .objs/closure.o
mv .objs/closure.d .deps
echo c++ -- cb/dumpTX.cpp
mkdir -p .deps
mkdir -p .objs
g++ -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -c cb/dumpTX.cpp -o .objs/dumpTX.o
mv .objs/dumpTX.d .deps
echo c++ -- cb/help.cpp
mkdir -p .deps
mkdir -p .objs
g++ -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -c cb/help.cpp -o .objs/help.o
mv .objs/help.d .deps
echo c++ -- cb/pristine.cpp
mkdir -p .deps
mkdir -p .objs
g++ -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -c cb/pristine.cpp -o .objs/pristine.o
mv .objs/pristine.d .deps
echo c++ -- cb/rawdump.cpp
mkdir -p .deps
mkdir -p .objs
g++ -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -c cb/rawdump.cpp -o .objs/rawdump.o
mv .objs/rawdump.d .deps
echo c++ -- cb/rewards.cpp
mkdir -p .deps
mkdir -p .objs
g++ -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -c cb/rewards.cpp -o .objs/rewards.o
mv .objs/rewards.d .deps
echo c++ -- cb/simpleStats.cpp
mkdir -p .deps
mkdir -p .objs
g++ -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -c cb/simpleStats.cpp -o .objs/simpleStats.o
mv .objs/simpleStats.d .deps
echo c++ -- cb/sql.cpp
mkdir -p .deps
mkdir -p .objs
g++ -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -c cb/sql.cpp -o .objs/sql.o
mv .objs/sql.d .deps
echo c++ -- cb/taint.cpp
mkdir -p .deps
mkdir -p .objs
g++ -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -c cb/taint.cpp -o .objs/taint.o
mv .objs/taint.d .deps
echo c++ -- cb/transactions.cpp
mkdir -p .deps
mkdir -p .objs
g++ -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -c cb/transactions.cpp -o .objs/transactions.o
mv .objs/transactions.d .deps
echo 'cc ' -- h9/blake.c
mkdir -p .deps
mkdir -p .objs
cc -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -w -c h9/blake.c -o .objs/blake.o
mv .objs/blake.d .deps
echo 'cc ' -- h9/bmw.c
mkdir -p .deps
mkdir -p .objs
cc -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -w -c h9/bmw.c -o .objs/bmw.o
mv .objs/bmw.d .deps
echo 'cc ' -- h9/cubehash.c
mkdir -p .deps
mkdir -p .objs
cc -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -w -c h9/cubehash.c -o .objs/cubehash.o
mv .objs/cubehash.d .deps
echo 'cc ' -- h9/echo.c
mkdir -p .deps
mkdir -p .objs
cc -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -w -c h9/echo.c -o .objs/echo.o
mv .objs/echo.d .deps
echo 'cc ' -- h9/groestl.c
mkdir -p .deps
mkdir -p .objs
cc -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -w -c h9/groestl.c -o .objs/groestl.o
mv .objs/groestl.d .deps
echo 'cc ' -- h9/jh.c
mkdir -p .deps
mkdir -p .objs
cc -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -w -c h9/jh.c -o .objs/jh.o
mv .objs/jh.d .deps
echo 'cc ' -- h9/keccak.c
mkdir -p .deps
mkdir -p .objs
cc -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -w -c h9/keccak.c -o .objs/keccak.o
mv .objs/keccak.d .deps
echo 'cc ' -- h9/luffa.c
mkdir -p .deps
mkdir -p .objs
cc -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -w -c h9/luffa.c -o .objs/luffa.o
mv .objs/luffa.d .deps
echo 'cc ' -- h9/shavite.c
mkdir -p .deps
mkdir -p .objs
cc -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -w -c h9/shavite.c -o .objs/shavite.o
mv .objs/shavite.d .deps
echo 'cc ' -- h9/simd.c
mkdir -p .deps
mkdir -p .objs
cc -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -w -c h9/simd.c -o .objs/simd.o
mv .objs/simd.d .deps
echo 'cc ' -- h9/skein.c
mkdir -p .deps
mkdir -p .objs
cc -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -w -c h9/skein.c -o .objs/skein.o
mv .objs/skein.d .deps
echo c++ -- scrypt/pbkdf2.cpp
mkdir -p .deps
mkdir -p .objs
g++ -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -c scrypt/pbkdf2.cpp -o .objs/pbkdf2.o
mv .objs/pbkdf2.d .deps
echo c++ -- scrypt/scrypt.cpp
mkdir -p .deps
mkdir -p .objs
g++ -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -c scrypt/scrypt.cpp -o .objs/scrypt.o
mv .objs/scrypt.d .deps
echo c++ -- callback.cpp
mkdir -p .deps
mkdir -p .objs
g++ -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -c callback.cpp -o .objs/callback.o
mv .objs/callback.d .deps
echo c++ -- opcodes.cpp
mkdir -p .deps
mkdir -p .objs
g++ -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -c opcodes.cpp -o .objs/opcodes.o
mv .objs/opcodes.d .deps
echo c++ -- option.cpp
mkdir -p .deps
mkdir -p .objs
g++ -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -c option.cpp -o .objs/option.o
mv .objs/option.d .deps
echo c++ -- parser.cpp
mkdir -p .deps
mkdir -p .objs
g++ -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -c parser.cpp -o .objs/parser.o
mv .objs/parser.d .deps
echo c++ -- rmd160.cpp
mkdir -p .deps
mkdir -p .objs
g++ -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -c rmd160.cpp -o .objs/rmd160.o
mv .objs/rmd160.d .deps
echo c++ -- sha256.cpp
mkdir -p .deps
mkdir -p .objs
g++ -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -c sha256.cpp -o .objs/sha256.o
mv .objs/sha256.d .deps
echo c++ -- util.cpp
mkdir -p .deps
mkdir -p .objs
g++ -MD -I. -DNDEBUG -DBITCOIN -DWANT_DENSE  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter   -c util.cpp -o .objs/util.o
mv .objs/util.d .deps
echo lnk -- parser 
g++ -s  -g0 -O6 -m64 -Wall -flto -msse3 -Wextra -Wformat -pedantic -std=c++0x -ffast-math -march=native -fno-check-new -funroll-loops -Wno-deprecated -fstrict-aliasing -Wformat-security -Wstrict-aliasing=2 -Wno-variadic-macros -fomit-frame-pointer -Wno-unused-variable -Wno-unused-parameter  -o parser .objs/allBalances.o .objs/closure.o .objs/dumpTX.o .objs/help.o .objs/pristine.o .objs/rawdump.o .objs/rewards.o .objs/simpleStats.o .objs/sql.o .objs/taint.o .objs/transactions.o .objs/blake.o .objs/bmw.o .objs/cubehash.o .objs/echo.o .objs/groestl.o .objs/jh.o .objs/keccak.o .objs/luffa.o .objs/shavite.o .objs/simd.o .objs/skein.o .objs/pbkdf2.o .objs/scrypt.o .objs/callback.o .objs/opcodes.o .objs/option.o .objs/parser.o .objs/rmd160.o .objs/sha256.o .objs/util.o  -lcrypto -ldl

**Comment by znort987** [comment]
I you're on ubuntu (I assume, given your prompt). It'd be useful to know which version:

    lsb_release -a

I would also like to see what the last phase (the link phase) does exactly on your box,
and in particular, which weird version of libcrypto it gets its hands on. (The likely issue
being that your librcrypto has become somehow corrupted).

To do this, edit the file called Makefile and 

    make clean
    make LOPT="-Wl,--verbose" >& MAKELOG.txt

Please paste the content of file MAKELOG.txt here.
Thanks.

**Comment by makabress** [comment]
hi 
and thank you 
yes im using Ubuntu 14.10 in VM

i will make the log file late this night
thank you
