### ISSUE TITLE
I get stuck at --  /usr/bin/ld: cannot find -lcrypto during the make

### ISSUE THREAD

**Issue by rascal777** [znort987/blockparser#38]
I get stuck at --  /usr/bin/ld: cannot find -lcrypto during the make

What is going on, and how can I get past this?

I tried to do gcc -lcrypto
and the result was file not found.  I then tried to install random crypto libraries, but no luck and I may have to uninstall them, because now I do gcc -lcrypto and the return is:  
In function `_start': /build/buildd/glibc-2.21/csu/../sysdeps/i386/start.S:111: undefined reference to `main'

**Comment by znort987** [comment]
If on ubuntu:
