### ISSUE TITLE
Removed

### ISSUE THREAD

**Issue by pstuermlinger** [znort987/blockparser#43]
removed

**Comment by znort987** [comment]
The code in the if block is code that does nothing useful: it just prints out progress statistics.and It's enough to trigger it every 10 blocks, and then to check if enough time has elapsedsince last progress report before putting out a new one.
The one line of code that actually does useful work on every block is outside of theif() { block (just after it in fact), unless I'm mistaken. 

```
On Sunday, April 10, 2016 1:29 PM, haggins <notifications@github.com> wrote:
```

 Hi,I'm just going through the code to educate myself.In function parseLongestChain() you start analyzing the chain from block height 10:while(likely(0!=blk)) {
        if(0==(blk->height % 10)) {
            ...
        }

```
    blk = blk->next;
```

}
In theory, a block with height 0 (the genesis block) satisfies the condition as well. However, the very first block within the loop isgNullBlock->next and therefore has a height of 1, resulting in ignoring block 0-9.
What is the idea behind this?—

**Comment by pstuermlinger** [comment]
Thank you. I just realised it after a couple of minutes after my post (as usual...) and removed its content ;)
