### ISSUE TITLE
"No targets specified and no makefile found."

### ISSUE THREAD

**Issue by emcor01** [znort987/blockparser#45]
I did everything as described in the readme, but it stops at this point:

user@ubuntu:~$ cd blockparser
user@ubuntu:~/blockparser$ make
make: **\* No targets specified and no makefile found.  Stop.

What is wrong?

**Comment by znort987** [comment]
./make
Note the "./" in front of make

```
On Saturday, June 11, 2016 10:09 AM, emcor01 <notifications@github.com> wrote:
```

 I did everything as described in the readme, but it stops at this point:user@ubuntu:~$ cd blockparser
user@ubuntu:~/blockparser$ make
make: **\* No targets specified and no makefile found. Stop.What is wrong?—
