### ISSUE TITLE
fatal: problem accessing directory /home/user/.bitcoin

### ISSUE THREAD

**Issue by emcor01** [znort987/blockparser#46]
I installed the blockparser but I cannot run any of the commands. I get this error message:

user@ubuntu:~$ cd blockparser
user@ubuntu:~/blockparser$ ./parser all

info: mem at start = 0.000 Gigs
info: starting command "allBalances"
fatal: problem accessing directory /home/user/.bitcoin
Aborted (core dumped)

I presume it doesnt find the blockchain files. I saved "blk00000.dat" and so on in this directory:
/home/user/user/Blockchain/blocks

I copied this blockchain from my windows 10 OS into the VMware Ubuntu.

I dont know why the filepath shows "user/user", I access the file actually by clicking only one such folder.
The blockparser readme says "You'll need a block chain somewhere on your hard drive." (but not where exactly).

I also tried to install the blockchain as recommended in the blockparser readme, but came only as far as this:

user@ubuntu:~$ git clone https://github.com/bitcoin/bitcoin
user@ubuntu:~$ cd bitcoin
user@ubuntu:~/bitcoin$ ./Makefile
bash: ./Makefile: No such file or directory

When I open the /bitcoin folder I can see the file Makefile.am . I dont know why it doesnt work.

**Comment by znort987** [comment]
First running blockparser in a VM is a generally bad idea unless you VM has very large amounts of RAM allocated toit (64G is good) and is capable of doing very efficient native I/Os (blockparser will chew through 80Gigs of data twice,typically)

Second, why install the blockchain in a directory of your own choosing and not where it's supposed to be, i.e. in the directory~/.bitcoin

Third, you do not need to install bitcoin (the software) in the VM. All you need is an up to date version of the blockchain. Therecommended way to do this in a VM is to mount your windoze blockchain directory inside the VM via whatever sharingmechanism your particular flavor of VM has (and on ~/.bitcoin, typically)

Generally speaking, blockparser was never really designed for non-technical users in general and _really_ never intented to beused by Windoze users in particular: there is a minimum technical level of skills required, such as being able to open a shell,creating directories from the command line, compiling software, etc ...

The point and click herd usually finds it easier to use online web-based version of the same thing such as the bitcoin rich listwebsite and others.

```
On Sunday, June 12, 2016 10:26 AM, emcor01 <notifications@github.com> wrote:
```

 I installed the blockparser but I cannot run any of the commands. I get this error message:user@ubuntu:~$ cd blockparser
user@ubuntu:~/blockparser$ ./parser allinfo: mem at start = 0.000 Gigs
info: starting command "allBalances"
fatal: problem accessing directory /home/user/.bitcoin
Aborted (core dumped)I presume it doesnt find the blockchain files. I saved "blk00000.dat" and so on in this directory:
/home/user/user/Blockchain/blocksI copied this blockchain from my windows 10 OS into the VMware Ubuntu.I dont know why the filepath shows "user/user", I access the file actually by clicking only one such folder.If I need to install the blockchain as recommended in the blockparser readme, then I need help how to do that.
I came only as far as this:user@ubuntu:~$ git clone https://github.com/bitcoin/bitcoin
user@ubuntu:~$ cd bitcoin
user@ubuntu:~/bitcoin$ ./Makefile
bash: ./Makefile: No such file or directoryWhen I open the folder I can see the file Makefile.am . I dont know why it doesnt work.—

**Comment by emcor01** [comment]
I saved the folder “blocks” in Home/.bitcoin . But I now get a new error message:

user@ubuntu:~/blockparser$ ./parser all

info: mem at start = 0.000 Gigs
info: starting command "allBalances"
info: loading block chain from directory: /home/user/.bitcoin
info: block chain size = 0.000 Gigs
info: initializing hash tables
info: estimated number of blocks = 0.00K
info: estimated number of transactions = 0.00M
info: done initializing hash tables - mem = 0.000 Gigs
info: pass 1 -- walk all blocks and build headers ...
warning: found no blocks - giving up   

The attached screenshot shows that the .bitcoin folder contains the blocks (as far as I see).

Can you please explain how to solve the new error?

Thank you,

![screenshot from 2016-06-12 03-57-46](https://cloud.githubusercontent.com/assets/19762403/15990736/7b8d5942-309d-11e6-9750-f3164d081915.png)
