### ISSUE TITLE
 warning: found no blocks - giving up (in VM)

### ISSUE THREAD

**Issue by emrng** [znort987/blockparser#49]
Hi there, 

I've found the same issue described at the bottom of this past one 

https://github.com/znort987/blockparser/issues/46

I had too many problems with the required dependencies in my physical machine, hence I decided to start your installation in a fresh install, where I haven't found any problem with dependencies at all.

I was trying your installation instructions when I got stuck at the same point (symbolic link to my host already made)

user@vm:~/blockparser$ ./parser transactions 06f1b66fa14429389cbffa656966993eab656f37

```
info: mem at start = 0.000 Gigs
info: starting command "transactions"
info: loading block chain from directory: /home/user/.bitcoin
info: block chain size = 0.000 Gigs
info: initializing hash tables
info: estimated number of blocks = 0.00K
info: estimated number of transactions = 0.00M
info: done initializing hash tables - mem = 0.000 Gigs
info: pass 1 -- walk all blocks and build headers ...
warning: found no blocks - giving up                                                       
user@vm:~/blockparser$ cat /etc/issue
Ubuntu 16.04 LTS \n \l

user@vm:~/blockparser$ 
```

BTW, I tipped you a few days ago from 1Eva

Cheers.

**Comment by emrng** [comment]
If using a VM is really that bad idea, I'd try this workaround:
1. install a new OS in a new physical partition
2. create a new partition (maybe using a whole disk) only for the blockchain (to be shared among different OS's)
3. move the blockchain to the new partition/hard drive
4. start the blockparser installation in the new physical OS binding the folder to the blockchain dir

**Comment by znort987** [comment]
The problem you're facing is basically that blockparser is not finding your blockchain.For blockparser to work, it needs a bitcoin-core compatible blockhain. Do you haveone installed in your VM ?

```
On Friday, July 15, 2016 10:21 PM, Eva <notifications@github.com> wrote:
```

 Hi there, I've found the same issue described at the bottom of this past one #46I had too many problems with the required dependencies in my physical machine, hence I decided to start your installation in a fresh install, where I haven't found any problem with dependencies at all.I was trying your installation instructions when I got stuck at the same point (symbolic link to my host already made)user@vm:~/blockparser$ ./parser transactions 06f1b66fa14429389cbffa656966993eab656f37info: mem at start = 0.000 Gigs
info: starting command "transactions"
info: loading block chain from directory: /home/user/.bitcoin
info: block chain size = 0.000 Gigs
info: initializing hash tables
info: estimated number of blocks = 0.00K
info: estimated number of transactions = 0.00M
info: done initializing hash tables - mem = 0.000 Gigs
info: pass 1 -- walk all blocks and build headers ...
warning: found no blocks - giving up  
user@vm:~/blockparser$ cat /etc/issue
Ubuntu 16.04 LTS \n \l

user@vm:~/blockparser$ 
BTW, I tipped you a few days ago from 1EvaCheers.—

**Comment by emrng** [comment]
For scalability concerns, I am setting up a full node in an AWS instance with Ubuntu. Not sure if using a docker image will actually speed up things for the blockchain setup.

Regarding the vm setup, I already checked the blockchain was accesible from the vm. Not sure what was the problem. Maybe some corruption on the data. 

Thank you for taking the time to help with this.
