### ISSUE TITLE
Python to visualize Data from Blockparser

### ISSUE THREAD

**Issue by emrng** [znort987/blockparser#53]
Hi!
Blockparser is all setup for me, using an AWS instance with Ubuntu 14.04 with a fresh install! However, to fully get the potential, I would like to visualize all the data extracted. Not sure which tool, or if there is something more suitable than others. 

If I'd have to choose between R and Python, I'd go for something made with Python.

(I know this gets a little out of the scope of your utility, but you may know much better than me about a tool for this)

**Comment by znort987** [comment]
Send me an e-mail 

`znort987@gmail.com`  

I can help you with Python.
