### ISSUE TITLE
mem not showing i have 1024 gb memory still error

### ISSUE THREAD

**Issue by aqui1991** [znort987/blockparser#94]
yadu@yadu-System-Product-Name:~/blockparser$ ./parser allBalances -a 100

info: mem at start = 0.000 Gigs
info: starting command "allBalances"
info: only taking into account transactions before block 100

info: loading block chain from directory: /media/yadu/btc/bitcoin
info: block chain size = 136.632 Gigs
info: initializing hash tables
Segmentation fault (core dumped)

**Comment by aqui1991** [comment]
yadu@yadu-System-Product-Name:~/blockparser$ ./parser simple

info: mem at start = 0.000 Gigs
info: starting command "simpleStats"
info: loading block chain from directory: /media/yadu/btc/bitcoin
info: block chain size = 136.632 Gigs
info: initializing hash tables
info: estimated number of blocks = 1073.54K
info: estimated number of transactions = 277.30M
info: done initializing hash tables - mem = 0.000 Gigs
info: pass 1 -- walk all blocks and build headers ...
 0.10% (0.13/130.30 Gigs) -- 119998 blocks -- 572.99 Megs/sec -- ETA 238 secs -- 0.20% (0.26/130.30 Gigs) -- 131237 blocks -- 1040.51 Megs/sec -- ETA 131 secs - 0.29% (0.38/130.30 Gigs) -- 136935 blocks -- 1487.70 Megs/sec -- ETA 92 secs -- 0.39% (0.51/130.30 Gigs) -- 142647 blocks -- 1898.78 Megs/sec -- ETA 72 secs -- 0.49% (0.64/130.30 Gigs) -- 149036 blocks -- 2263.51 Megs/sec -- ETA 60 secs -- 0.59% (0.77/130.30 Gigs) -- 156512 blocks -- 2574.81 Megs/sec -- ETA 53 secs -- 0.69% (0.90/130.30 Gigs) -- 163729 blocks -- 2860.76 Megs/sec -- ETA 47 secs -- 0.79% (1.02/130.30 Gigs) -- 169938 blocks -- 3141.04 Megs/sec -- ETA 43 secs -- 0.88% (1.15/130.30 Gigs) -- 176086 blocks -- 3402.67 Megs/sec -- ETA 40 secs -- 0.98% (1.28/130.30 Gigs) -- 180040 blocks -- 3692.93 Megs/sec -- ETA 37 secs -- 1.08% (1.41/130.30 Gigs) -- 181541 blocks -- 4025.69 Megs/sec -- ETA 34 secs -- 1.18% (1.54/130.30 Gigs) -- 183102 blocks -- 4350.00 Megs/sec -- ETA 31 secs -- 1.28% (1.66/130.30 Gigs) -- 184467 blocks -- 4673.41 Megs/sec -- ETA 29 secs

**Comment by aqui1991** [comment]
./parser simple 
works apart from this nothing works
please assist

**Comment by salber** [comment]
replace or delete BN_CTX_init
